---
name: "t-api"

services:
  t-invest-bot:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_t-invest-bot
    hostname: t-invest-bot
    pull_policy: always
    networks:
      - default
    volumes:
      - /Users/user/docker/data/t-invest-bot:/app/data
